name: untitled1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.0.3
  cupertino_icons: ^1.0.6
  sqflite: ^2.0.0+3
  path_provider: ^2.0.5
  camera: ^0.10.0+1
  permission_handler: ^10.2.0
  flutter_facebook_auth: ^5.0.2
  google_sign_in: ^5.2.3
  image_picker: ^0.8.4+2
  shared_preferences: ^2.0.12
  flutter_local_notifications: ^13.0.0
  flutter_datetime_picker: ^1.5.1
  timezone: ^0.9.3
  http: ^0.13.6
  crypto: ^3.0.1
  pointycastle: ^3.4.1
  mailer: ^5.1.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
